<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemsSeeder extends Seeder
{
    public function run()
    {
        $items = [
            ['id' => 1, 'category_id' => 47, 'item_name' => 'Chicken Salad', 'price' => 5.99, 'description' => 'N/A'],
            ['id' => 2, 'category_id' => 47, 'item_name' => 'Coleslaw Salad', 'price' => 1.99, 'description' => 'N/A'],
            ['id' => 3, 'category_id' => 47, 'item_name' => 'Prawn Cocktail', 'price' => 6.69, 'description' => 'N/A'],
            ['id' => 4, 'category_id' => 47, 'item_name' => 'Side Salad', 'price' => 2.29, 'description' => 'N/A'],
            ['id' => 5, 'category_id' => 47, 'item_name' => 'Tuna Salad', 'price' => 5.69, 'description' => 'N/A'],
            ['id' => 6, 'category_id' => 48, 'item_name' => 'Chicken Kebabs', 'price' => 8.99, 'description' => 'Tender pieces of Marinated Chicken served in Pitta with Salad & choice of Garlic or Chilli Sauce'],
            ['id' => 7, 'category_id' => 48, 'item_name' => 'Doner', 'price' => 6.99, 'description' => 'Slices of high quality Doner Kebab, Served with Salad in a Pitta Bread & choice of Garlic or Chilli Sauce'],
            ['id' => 8, 'category_id' => 48, 'item_name' => 'Doner & Fries', 'price' => 6.99, 'description' => 'Choice of Garlic or Chilli Sauce'],
            ['id' => 9, 'category_id' => 48, 'item_name' => "Morris's Special Shoebox Mixed Kebab", 'price' => 10.99, 'description' => 'A mixture of Chicken and Doner Kebab, served with Fried Onion, Fried Mushroom, Fried Peppers with salad and Nan Bread & choice of Garlic or Chilli Sauce'],
            ['id' => 10, 'category_id' => 48, 'item_name' => 'Shoebox Mixed Kebabs', 'price' => 9.99, 'description' => 'A mixture of Chicken and Doner Kebab, served with Salad in Nan Bread & choice of Garlic or Chilli Sauce'],
            ['id' => 11, 'category_id' => 49, 'item_name' => 'Americana 12oz', 'price' => 8.49, 'description' => 'Topped with Double Slice of Cheese, Fried Onion All Burgers served in a bun with French Fries and Salad'],
            ['id' => 12, 'category_id' => 49, 'item_name' => 'Americana 6oz', 'price' => 7.49, 'description' => 'Topped with Double Slice of Cheese, Fried Onion All Burgers served in a bun with French Fries and Salad'],
            ['id' => 13, 'category_id' => 49, 'item_name' => 'Boston Burger 12oz', 'price' => 8.79, 'description' => 'Topped with Double Slice of Cheese & Bacon All Burgers served in a bun with French Fries and Salad'],
            ['id' => 14, 'category_id' => 49, 'item_name' => 'Boston Burger 6oz', 'price' => 7.79, 'description' => 'Topped with Double Slice of Cheese, Bacon & Pepperoni All Burgers served in a bun with French Fries and Salad'],
            ['id' => 15, 'category_id' => 49, 'item_name' => 'Cheese Burger 12oz', 'price' => 8.39, 'description' => 'Topped with Double Slice of Cheese All Burgers served in a bun with French Fries and Salad'],
            ['id' => 16, 'category_id' => 49, 'item_name' => 'Cheese Burger 6oz', 'price' => 7.39, 'description' => 'Topped with Double Slice of Cheese All Burgers served in a bun with French Fries and Salad'],
            ['id' => 17, 'category_id' => 49, 'item_name' => 'Chicken Burger 12oz', 'price' => 6.79, 'description' => '100% Chicken Filled Burger served with Heinz Mayonnaise All Burgers served in a bun with French Fries and Salad'],
            ['id' => 18, 'category_id' => 49, 'item_name' => 'Chicken Burger 6oz', 'price' => 5.99, 'description' => '100% Chicken Filled Burger served with Heinz Mayonnaise All Burgers served in a bun with French Fries and Salad'],
            ['id' => 19, 'category_id' => 49, 'item_name' => 'Chilli Burger 12oz', 'price' => 8.49, 'description' => 'Topped with Chilli Con Carne Sauce All Burgers served in a bun with French Fries and Salad'],
            ['id' => 20, 'category_id' => 49, 'item_name' => 'Chilli Burger 6oz', 'price' => 7.49, 'description' => 'Topped with Chilli Con Carne Sauce All Burgers served in a bun with French Fries and Salad'],
            ['id' => 21, 'category_id' => 49, 'item_name' => 'De-Luxe Grilled Burger 12oz', 'price' => 7.99, 'description' => 'All Burgers served in a bun with French Fries and Salad'],
            ['id' => 22, 'category_id' => 49, 'item_name' => 'De-Luxe Grilled Burger 6oz', 'price' => 6.99, 'description' => 'All Burgers served in a bun with French Fries and Salad'],
            ['id' => 23, 'category_id' => 49, 'item_name' => 'DONER BURGER 12oz', 'price' => 8.79, 'description' => 'Double Slice of Cheese and Doner'],
            ['id' => 24, 'category_id' => 49, 'item_name' => 'DONER BURGER 6oz', 'price' => 7.79, 'description' => 'Double Slice of Cheese and Doner'],
            ['id' => 25, 'category_id' => 49, 'item_name' => 'Double Decker Chicken Burger 12oz', 'price' => 7.79, 'description' => '100% Chicken Fillet Burgers topped with Slice of Cheese, Hash Brown & Heinz Mayo All Burgers served in a bun with French Fries and Salad'],
            ['id' => 26, 'category_id' => 49, 'item_name' => 'Double Decker Chicken Burger 6oz', 'price' => 6.59, 'description' => '100% Chicken Fillet Burgers topped with Slice of Cheese, Hash Brown & Heinz Mayo All Burgers served in a bun with French Fries and Salad'],
            ['id' => 27, 'category_id' => 49, 'item_name' => "Five 'O' 12oz", 'price' => 8.49, 'description' => 'Topped with Pineapple ring & Double Slice of Cheese All Burgers served in a bun with French Fries and Salad'],
            ['id' => 28, 'category_id' => 49, 'item_name' => "Five 'O' 6oz", 'price' => 7.49, 'description' => 'Topped with Pineapple ring & Double Slice of Cheese All Burgers served in a bun with French Fries and Salad'],
            ['id' => 29, 'category_id' => 49, 'item_name' => 'Italiano 12oz', 'price' => 8.79, 'description' => 'Topped with Double Slice of Cheese & Pepperoni All Burgers served in a bun with French Fries and Salad'],
            ['id' => 30, 'category_id' => 49, 'item_name' => 'Italiano 6oz', 'price' => 7.79, 'description' => 'Topped with Double Slice of Cheese & Pepperoni All Burgers served in a bun with French Fries and Salad'],
            ['id' => 31, 'category_id' => 49, 'item_name' => 'Mega Burger 12oz', 'price' => 9.99, 'description' => 'Triple Burger topped with triple Slice of Cheese & Fried Onion, Fried Mushrooms & Bacon All Burgers served in a bun with French Fries and Salad'],
            ['id' => 32, 'category_id' => 49, 'item_name' => 'Milano Burger 12oz', 'price' => 8.99, 'description' => 'Topped with Double Slice of Cheese, Bacon & Pepperoni All Burgers served in a bun with French Fries and Salad'],
            ['id' => 33, 'category_id' => 49, 'item_name' => 'Milano Burger 6oz', 'price' => 7.99, 'description' => 'Topped with Double Slice of Cheese, Bacon & Pepperoni All Burgers served in a bun with French Fries and Salad'],
            ['id' => 34, 'category_id' => 49, 'item_name' => "Morris's Special Burger 12oz", 'price' => 8.99, 'description' => 'Beef Burger & Chicken Burger topped with Double Slice of Cheese & Mayo All Burgers served in a bun with French Fries and Salad'],
            ['id' => 35, 'category_id' => 49, 'item_name' => 'Portuguese Spicy Chicken Burger 12oz', 'price' => 7.79, 'description' => 'Topped with Pepperoni, a slice of Cheese and Heinz Mayo All Burgers served in a bun with French Fries and Salad'],
            ['id' => 36, 'category_id' => 49, 'item_name' => 'Portuguese Spicy Chicken Burger 6oz', 'price' => 6.69, 'description' => 'Topped with Pepperoni, a slice of Cheese and Heinz Mayo All Burgers served in a bun with French Fries and Salad'],
            ['id' => 37, 'category_id' => 49, 'item_name' => 'Ringo Burger NEW 12oz', 'price' => 8.99, 'description' => 'Beef Burger with Onion Rings and Double Cheese All Burgers served in a bun with French Fries and Salad'],
            ['id' => 38, 'category_id' => 49, 'item_name' => 'Ringo Burger NEW 6oz', 'price' => 7.99, 'description' => 'Beef Burger with Onion Rings and Double Cheese All Burgers served in a bun with French Fries and Salad'],
            ['id' => 39, 'category_id' => 49, 'item_name' => 'Smokey Burger 12oz', 'price' => 8.20, 'description' => 'Char-grilled Burger topped with Barbecue Sauce All Burgers served in a bun with French Fries and Salad'],
            ['id' => 40, 'category_id' => 49, 'item_name' => 'Smokey Burger 6oz', 'price' => 7.20, 'description' => 'Char-grilled Burger topped with Barbecue Sauce All Burgers served in a bun with French Fries and Salad'],
            ['id' => 41, 'category_id' => 49, 'item_name' => 'Special Chicken Burger 12oz', 'price' => 6.99, 'description' => '100% Chicken Fillet Burger served with Bacon, Double Slice of Cheeze & Heinz Mayo All Burgers served in a bun with French Fries and Salad'],
            ['id' => 42, 'category_id' => 49, 'item_name' => 'Special Chicken Burger 6oz', 'price' => 5.99, 'description' => '100% Chicken Fillet Burger served with Bacon, Double Slice of Cheeze & Heinz Mayo All Burgers served in a bun with French Fries and Salad'],
            ['id' => 43, 'category_id' => 49, 'item_name' => 'Spicy Chicken Burger 12oz', 'price' => 7.39, 'description' => '100% Spicy Chicken Fillet Burger served with Heinz Mayonnaise All Burgers served in a bun with French Fries and Salad'],
            ['id' => 44, 'category_id' => 49, 'item_name' => 'Spicy Chicken Burger 6oz', 'price' => 6.39, 'description' => '100% Spicy Chicken Fillet Burger served with Heinz Mayonnaise All Burgers served in a bun with French Fries and Salad'],
            ['id' => 45, 'category_id' => 49, 'item_name' => 'Swiss Burger NEW 12oz', 'price' => 8.79, 'description' => 'Beef Burger, Double Cheese, Fried Mushroom & Garlic All Burgers served in a bun with French Fries and Salad'],
            ['id' => 46, 'category_id' => 49, 'item_name' => 'Swiss Burger NEW 6oz', 'price' => 7.79, 'description' => 'Beef Burger, Double Cheese, Fried Mushroom & Garlic All Burgers served in a bun with French Fries and Salad'],
            ['id' => 47, 'category_id' => 50, 'item_name' => '3 Sausage & Chips', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 48, 'category_id' => 50, 'item_name' => '4 Chicken Nuggets & Chips', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 49, 'category_id' => 50, 'item_name' => '4 Fish Fingers & Chips', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 50, 'category_id' => 50, 'item_name' => 'Kebab Meat & Chips', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 51, 'category_id' => 50, 'item_name' => 'Mini Margherita', 'price' => 5.99, 'description' => 'N/A'],
            ['id' => 52, 'category_id' => 40, 'item_name' => 'BBQ Chicken Wings', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 53, 'category_id' => 40, 'item_name' => 'BBQ CHICKEN WINGS', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 54, 'category_id' => 40, 'item_name' => 'BREADED GARLIC MUSHROOM', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 55, 'category_id' => 40, 'item_name' => 'Deep Fried Mozzarella', 'price' => 4.49, 'description' => 'Served with Salad & Sweet Chilli Sauce'],
            ['id' => 56, 'category_id' => 40, 'item_name' => 'DEEP FRIED MOZZARELLA', 'price' => 4.49, 'description' => 'Served with Salad & Sweet Chilli Sauce'],
            ['id' => 57, 'category_id' => 40, 'item_name' => 'Garlic Bread', 'price' => 4.69, 'description' => 'N/A'],
            ['id' => 58, 'category_id' => 40, 'item_name' => 'GARLIC BREAD', 'price' => 4.69, 'description' => 'N/A'],
            ['id' => 59, 'category_id' => 40, 'item_name' => 'Garlic Bread Pomador', 'price' => 4.79, 'description' => 'N/A'],
            ['id' => 60, 'category_id' => 40, 'item_name' => 'GARLIC BREAD POMADOR', 'price' => 4.79, 'description' => 'Tomato'],
            ['id' => 61, 'category_id' => 40, 'item_name' => 'Garlic Bread Supreme', 'price' => 4.99, 'description' => 'N/A'],
            ['id' => 62, 'category_id' => 40, 'item_name' => 'GARLIC BREAD SUPREME', 'price' => 4.99, 'description' => 'Cheese'],
            ['id' => 63, 'category_id' => 40, 'item_name' => 'Garlic Mushrooms', 'price' => 3.99, 'description' => 'N/A'],
            ['id' => 64, 'category_id' => 40, 'item_name' => 'GARLIC MUSHROOMS', 'price' => 3.99, 'description' => 'N/A'],
            ['id' => 65, 'category_id' => 40, 'item_name' => 'Garlic Mushrooms Supreme', 'price' => 4.49, 'description' => 'N/A'],
            ['id' => 66, 'category_id' => 40, 'item_name' => 'GARLIC MUSHROOMS SUPREME', 'price' => 4.49, 'description' => 'Cheese'],
            ['id' => 67, 'category_id' => 40, 'item_name' => "JACK DANIEL'S CHICKEN WINGS", 'price' => 5.89, 'description' => 'N/A'],
            ['id' => 68, 'category_id' => 40, 'item_name' => 'JALAPENO POPPERS', 'price' => 4.89, 'description' => 'Served with Salad & Sweet Chilli Sauce'],
            ['id' => 69, 'category_id' => 40, 'item_name' => 'Nachos', 'price' => 3.49, 'description' => 'Topped with Mixed Cheese, Italian Sauce & Jalapeno'],
            ['id' => 70, 'category_id' => 40, 'item_name' => 'Special Garlic Bread', 'price' => 5.99, 'description' => 'N/A'],
            ['id' => 71, 'category_id' => 40, 'item_name' => 'SPECIAL GARLIC BREAD', 'price' => 5.99, 'description' => '4 Different Cheeses'],
            ['id' => 72, 'category_id' => 40, 'item_name' => 'Special Nachos', 'price' => 4.49, 'description' => 'Topped with Mixed Cheese, Italian Sauce, Chilli Con Carne & Jalapeno'],
            ['id' => 73, 'category_id' => 40, 'item_name' => 'Spicy Tomato Garlic Bread', 'price' => 4.89, 'description' => 'N/A'],
            ['id' => 74, 'category_id' => 40, 'item_name' => 'SPICY TOMATO GARLIC BREAD', 'price' => 4.89, 'description' => 'N/A'],
            ['id' => 75, 'category_id' => 59, 'item_name' => '7Up', 'price' => 1.50, 'description' => 'Cans'],
            ['id' => 76, 'category_id' => 59, 'item_name' => 'Bottle', 'price' => 2.99, 'description' => '1.5ltr Pepsi'],
            ['id' => 77, 'category_id' => 59, 'item_name' => 'Dr Pepper', 'price' => 1.50, 'description' => 'Cans'],
            ['id' => 78, 'category_id' => 59, 'item_name' => 'Fanta', 'price' => 1.50, 'description' => 'Cans'],
            ['id' => 79, 'category_id' => 59, 'item_name' => 'Lilt', 'price' => 1.50, 'description' => 'Cans'],
            ['id' => 80, 'category_id' => 59, 'item_name' => 'Pepsi', 'price' => 1.50, 'description' => 'Cans'],
            ['id' => 81, 'category_id' => 60, 'item_name' => '1000 Island Dressing', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 82, 'category_id' => 60, 'item_name' => 'BBQ Sauce', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 83, 'category_id' => 60, 'item_name' => 'Chilli Sauce', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 84, 'category_id' => 60, 'item_name' => 'Garlic Mayo', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 85, 'category_id' => 60, 'item_name' => 'Mayonnaise', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 86, 'category_id' => 60, 'item_name' => 'Relish', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 87, 'category_id' => 60, 'item_name' => 'Sweet Chilli Sauce', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 88, 'category_id' => 60, 'item_name' => 'Tomato Sauce', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 89, 'category_id' => 60, 'item_name' => 'Yoghurt Sauce', 'price' => 0.80, 'description' => 'N/A'],
            ['id' => 90, 'category_id' => 42, 'item_name' => 'Chicken Feast', 'price' => 8.99, 'description' => 'Skewered Chicken kebabs (Breast), served with Chips Salad & Coleslaw'],
            ['id' => 91, 'category_id' => 42, 'item_name' => 'Chicken Nuggets', 'price' => 6.89, 'description' => 'Deep Fried Chicken Nuggets served with Chips Salad & Coleslaw'],
            ['id' => 92, 'category_id' => 42, 'item_name' => 'Chilli-Con-Carne (Portion)', 'price' => 6.89, 'description' => 'Served with Pizza Bread or Chips'],
            ['id' => 93, 'category_id' => 42, 'item_name' => 'Golden Chicken', 'price' => 7.99, 'description' => 'Deep Fried Fillets of Chicken in Bread Crumbs served with Chips Salad & Coleslaw'],
            ['id' => 94, 'category_id' => 42, 'item_name' => 'Scampi', 'price' => 6.99, 'description' => 'Breaded Scampi, served with Chips Salad & Coleslaw'],
            ['id' => 95, 'category_id' => 61, 'item_name' => 'Chocolate calzone', 'price' => 4.59, 'description' => 'N/A'],
            ['id' => 96, 'category_id' => 61, 'item_name' => 'Chocolate Fudge Cake', 'price' => 2.99, 'description' => '1 Slice'],
            ['id' => 97, 'category_id' => 61, 'item_name' => 'Tiramisu', 'price' => 3.99, 'description' => 'Served with Single Cream'],
            ['id' => 98, 'category_id' => 43, 'item_name' => 'Cheesy Chips', 'price' => 3.99, 'description' => 'N/A'],
            ['id' => 99, 'category_id' => 43, 'item_name' => 'Curly Fries', 'price' => 3.59, 'description' => 'Choice of Dip'],
            ['id' => 100, 'category_id' => 43, 'item_name' => 'French Fries', 'price' => 2.80, 'description' => 'N/A'],
            ['id' => 101, 'category_id' => 43, 'item_name' => 'Jalapeño Peppers', 'price' => 4.89, 'description' => 'N/A'],
            ['id' => 102, 'category_id' => 43, 'item_name' => 'Onion Rings', 'price' => 2.99, 'description' => 'Small'],
            ['id' => 103, 'category_id' => 43, 'item_name' => 'Potato Wedges', 'price' => 3.59, 'description' => 'Choice of Dip'],
            ['id' => 104, 'category_id' => 43, 'item_name' => 'Potato Wedges Cheese & Bacon', 'price' => 4.69, 'description' => 'N/A'],
            ['id' => 105, 'category_id' => 87, 'item_name' => 'CHICKEN & BACON', 'price' => 6.99, 'description' => '(Choice of dressing)'],
            ['id' => 106, 'category_id' => 87, 'item_name' => 'CHICKEN & DONNER', 'price' => 6.99, 'description' => '(Choice of dressing)'],
            ['id' => 107, 'category_id' => 87, 'item_name' => 'CHICKEN TIKKA WRAP', 'price' => 6.99, 'description' => '(Choice of dressing)'],
            ['id' => 108, 'category_id' => 87, 'item_name' => 'CHICKEN WRAP', 'price' => 6.99, 'description' => 'chicken kebab and choice of dressing'],
            ['id' => 109, 'category_id' => 87, 'item_name' => 'DONNER WRAP', 'price' => 6.99, 'description' => '(Choice of dressing)'],
            ['id' => 110, 'category_id' => 44, 'item_name' => 'Lasagna', 'price' => 7.99, 'description' => 'Layers of pasta, bolognese sauce & bechamel sauce topped with parmesan cheese & cheese'],
            ['id' => 111, 'category_id' => 44, 'item_name' => 'Spaghetti Bolognese', 'price' => 7.99, 'description' => 'Spaghetti, bolognese sauce, parmesan cheese & cheese'],
            ['id' => 112, 'category_id' => 88, 'item_name' => 'Al Funghi Parmesan', 'price' => 9.99, 'description' => 'Mushroom and Garlic and melted mozzarella served with chips, italian salad and coleslaw.'],
            ['id' => 113, 'category_id' => 88, 'item_name' => 'Hot Shot Parmesan', 'price' => 9.99, 'description' => 'onion, Green Peppers & Jalapeños and melted mozzarella served with chips, italian salad and coleslaw.'],
            ['id' => 114, 'category_id' => 88, 'item_name' => 'Parmesan Chicken', 'price' => 8.99, 'description' => 'Breaded Chicken in white sauce and melted mozzarella served with chips, salad and coleslaw.'],
            ['id' => 115, 'category_id' => 45, 'item_name' => 'Al Funghi 11" Deep Pan', 'price' => 8.69, 'description' => 'Mushrooms'],
            ['id' => 116, 'category_id' => 45, 'item_name' => 'Al Funghi 11" Thin', 'price' => 7.69, 'description' => 'Mushrooms'],
            ['id' => 117, 'category_id' => 45, 'item_name' => 'Al Funghi Family Size 16"', 'price' => 15.38, 'description' => 'Mushrooms'],
            ['id' => 118, 'category_id' => 45, 'item_name' => 'BBQ Chicken 11" Deep Pan', 'price' => 9.49, 'description' => 'BBQ Chicken Chicken, BBQ Sauce'],
            ['id' => 119, 'category_id' => 45, 'item_name' => 'BBQ Chicken 11" Thin', 'price' => 8.49, 'description' => 'BBQ Chicken Chicken, BBQ Sauce'],
            ['id' => 120, 'category_id' => 45, 'item_name' => 'BBQ Chicken Family Size 16"', 'price' => 16.98, 'description' => 'BBQ Chicken Chicken, BBQ Sauce'],
            ['id' => 121, 'category_id' => 45, 'item_name' => 'BBQ Pulled Pork 11" Deep Pan', 'price' => 11.99, 'description' => 'BBQ Pulled Pork BBQ Sauce, Pulled Pork, Green Peppers & Sweetcorn'],
            ['id' => 122, 'category_id' => 45, 'item_name' => 'BBQ Pulled Pork 11" Thin', 'price' => 10.99, 'description' => 'BBQ Pulled Pork BBQ Sauce, Pulled Pork, Green Peppers & Sweetcorn'],
            ['id' => 123, 'category_id' => 45, 'item_name' => 'BBQ Pulled Pork Family Size 16"', 'price' => 19.99, 'description' => 'BBQ Pulled Pork BBQ Sauce, Pulled Pork, Green Peppers & Sweetcorn'],
            ['id' => 124, 'category_id' => 45, 'item_name' => 'Bolognese 11" Deep Pan', 'price' => 8.99, 'description' => 'Bolognese Bolognese Sauce'],
            ['id' => 125, 'category_id' => 45, 'item_name' => 'Bolognese 11" Thin', 'price' => 7.99, 'description' => 'Bolognese Bolognese Sauce'],
            ['id' => 126, 'category_id' => 45, 'item_name' => 'Bolognese Family Size 16"', 'price' => 15.98, 'description' => 'Bolognese Bolognese Sauce'],
            ['id' => 127, 'category_id' => 45, 'item_name' => 'Chilli 11" Deep Pan', 'price' => 8.99, 'description' => 'Chilli Chilli Con Carne Sauce'],
            ['id' => 128, 'category_id' => 45, 'item_name' => 'Chilli 11" Thin', 'price' => 7.99, 'description' => 'Chilli Chilli Con Carne Sauce'],
            ['id' => 129, 'category_id' => 45, 'item_name' => 'Chilli Family Size 16"', 'price' => 15.98, 'description' => 'Chilli Chilli Con Carne Sauce'],
            ['id' => 130, 'category_id' => 45, 'item_name' => 'Death By Garlic 11" Deep Pan', 'price' => 9.49, 'description' => 'Death By Garlic Torn Chicken Breast and Mushrooms laid on Pizza Garlic Sauce topped with Italian Mixed Cheese'],
            ['id' => 131, 'category_id' => 45, 'item_name' => 'Death By Garlic 11" Thin', 'price' => 8.49, 'description' => 'Death By Garlic Torn Chicken Breast and Mushrooms laid on Pizza Garlic Sauce topped with Italian Mixed Cheese'],
            ['id' => 132, 'category_id' => 45, 'item_name' => 'Death By Garlic Family Size 16"', 'price' => 16.98, 'description' => 'Death By Garlic Torn Chicken Breast and Mushrooms laid on Pizza Garlic Sauce topped with Italian Mixed Cheese'],
            ['id' => 133, 'category_id' => 45, 'item_name' => 'Garlic Sausage 11" Deep Pan', 'price' => 8.99, 'description' => 'Garlic Sausage, Onions'],
            ['id' => 134, 'category_id' => 45, 'item_name' => 'Garlic Sausage 11" Thin', 'price' => 7.99, 'description' => 'Garlic Sausage, Onions'],
            ['id' => 135, 'category_id' => 45, 'item_name' => 'Garlic Sausage Family Size 16"', 'price' => 15.98, 'description' => 'Garlic Sausage, Onions'],
            ['id' => 136, 'category_id' => 45, 'item_name' => 'Hot Lover 11" Deep Pan', 'price' => 9.49, 'description' => 'Hot Lover Pepperoni, Spicy Beef, Onions, Green Peppers, Cheddar Cheeese & Jalapenos'],
            ['id' => 137, 'category_id' => 45, 'item_name' => 'Hot Lover 11" Thin', 'price' => 8.49, 'description' => 'Hot Lover Pepperoni, Spicy Beef, Onions, Green Peppers, Cheddar Cheeese & Jalapenos'],
            ['id' => 138, 'category_id' => 45, 'item_name' => 'Hot Lover Family Size 16"', 'price' => 16.98, 'description' => 'Hot Lover Pepperoni, Spicy Beef, Onions, Green Peppers, Cheddar Cheeese & Jalapenos'],
            ['id' => 139, 'category_id' => 45, 'item_name' => 'Italian Job 11" Deep Pan', 'price' => 9.99, 'description' => 'Italian Job Grilled Bacon & Pepperoni, Spicy Beef, Peppers'],
            ['id' => 140, 'category_id' => 45, 'item_name' => 'Italian Job 11" Thin', 'price' => 8.99, 'description' => 'Italian Job Grilled Bacon & Pepperoni, Spicy Beef, Peppers'],
            ['id' => 141, 'category_id' => 45, 'item_name' => 'Italian Job Family Size 16"', 'price' => 17.98, 'description' => 'Italian Job Grilled Bacon & Pepperoni, Spicy Beef, Peppers'],
            ['id' => 142, 'category_id' => 45, 'item_name' => 'Margherita 11" Deep Pan', 'price' => 7.99, 'description' => 'Cheese, Tomato and Herbs'],
            ['id' => 143, 'category_id' => 45, 'item_name' => 'Margherita 11" Thin', 'price' => 6.99, 'description' => 'Cheese, Tomato and Herbs'],
            ['id' => 144, 'category_id' => 45, 'item_name' => 'Margherita Family Size 16"', 'price' => 13.98, 'description' => 'Cheese, Tomato and Herbs'],
            ['id' => 145, 'category_id' => 45, 'item_name' => 'Meat Feast 11" Deep Pan', 'price' => 9.99, 'description' => 'Meat Feast Ham, Salami, Garlic Sausage, Pepperoni, Spicy Beef'],
            ['id' => 146, 'category_id' => 45, 'item_name' => 'Meat Feast 11" Thin', 'price' => 8.99, 'description' => 'Meat Feast Ham, Salami, Garlic Sausage, Pepperoni, Spicy Beef'],
            ['id' => 147, 'category_id' => 45, 'item_name' => 'Meat Feast Family Size 16"', 'price' => 17.98, 'description' => 'Meat Feast Ham, Salami, Garlic Sausage, Pepperoni, Spicy Beef'],
            ['id' => 148, 'category_id' => 45, 'item_name' => "Morris's Special 11\" Deep Pan", 'price' => 10.99, 'description' => "Morris's Special Chef's own Preparation"],
            ['id' => 149, 'category_id' => 45, 'item_name' => "Morris's Special 11\" Thin", 'price' => 9.99, 'description' => "Morris's Special Chef's own Preparation"],
            ['id' => 150, 'category_id' => 45, 'item_name' => "Morris's Special Family Size 16\"", 'price' => 19.98, 'description' => "Morris's Special Chef's own Preparation"],
            ['id' => 151, 'category_id' => 45, 'item_name' => 'Passion Pepperoni 11" Deep Pan', 'price' => 10.99, 'description' => 'Passion Pepperoni 2 layers of Pepperoni & 2 layers of Cheese'],
            ['id' => 152, 'category_id' => 45, 'item_name' => 'Passion Pepperoni 11" Thin', 'price' => 9.99, 'description' => 'Passion Pepperoni 2 layers of Pepperoni & 2 layers of Cheese'],
            ['id' => 153, 'category_id' => 45, 'item_name' => 'Passion Pepperoni Family Size 16"', 'price' => 19.98, 'description' => 'Passion Pepperoni 2 layers of Pepperoni & 2 layers of Cheese'],
            ['id' => 154, 'category_id' => 45, 'item_name' => 'Pentathlon 11" Deep Pan', 'price' => 9.99, 'description' => 'Pentathlon Mushrooms, Ham, Chicken, Pepperoni'],
            ['id' => 155, 'category_id' => 45, 'item_name' => 'Pentathlon 11" Thin', 'price' => 8.99, 'description' => 'Pentathlon Mushrooms, Ham, Chicken, Pepperoni'],
            ['id' => 156, 'category_id' => 45, 'item_name' => 'Pentathlon Family Size 16"', 'price' => 17.98, 'description' => 'Pentathlon Mushrooms, Ham, Chicken, Pepperoni'],
            ['id' => 157, 'category_id' => 45, 'item_name' => 'Pepperoni 11" Deep Pan', 'price' => 9.99, 'description' => 'Pepperoni Pepperoni Sausage'],
            ['id' => 158, 'category_id' => 45, 'item_name' => 'Pepperoni 11" Thin', 'price' => 8.99, 'description' => 'Pepperoni Pepperoni Sausage'],
            ['id' => 159, 'category_id' => 45, 'item_name' => 'Pepperoni Family Size 16"', 'price' => 17.98, 'description' => 'Pepperoni Pepperoni Sausage'],
            ['id' => 160, 'category_id' => 45, 'item_name' => 'Pollo 11" Deep Pan', 'price' => 8.99, 'description' => 'Chicken, Sweetcorn Pollo'],
            ['id' => 161, 'category_id' => 45, 'item_name' => 'Pollo 11" Thin', 'price' => 7.99, 'description' => 'Chicken, Sweetcorn Pollo'],
            ['id' => 162, 'category_id' => 45, 'item_name' => 'Pollo A La Pepper 11" Deep Pan', 'price' => 8.99, 'description' => 'Pollo A La Pepper Spicy Chicken and Peppers'],
            ['id' => 163, 'category_id' => 45, 'item_name' => 'Pollo A La Pepper 11" Thin', 'price' => 7.99, 'description' => 'Pollo A La Pepper Spicy Chicken and Peppers'],
            ['id' => 164, 'category_id' => 45, 'item_name' => 'Pollo A La Pepper Family Size 16"', 'price' => 15.98, 'description' => 'Pollo A La Pepper Spicy Chicken and Peppers'],
            ['id' => 165, 'category_id' => 45, 'item_name' => 'Pollo Family Size 16"', 'price' => 15.98, 'description' => 'Chicken, Sweetcorn Pollo'],
            ['id' => 166, 'category_id' => 45, 'item_name' => 'Pollo Funghi 11" Deep Pan', 'price' => 8.99, 'description' => 'Pollo Funghi Chicken & Mushroom'],
            ['id' => 167, 'category_id' => 45, 'item_name' => 'Pollo Funghi 11" Thin', 'price' => 7.99, 'description' => 'Pollo Funghi Chicken & Mushroom'],
            ['id' => 168, 'category_id' => 45, 'item_name' => 'Pollo Funghi Family Size 16"', 'price' => 15.98, 'description' => 'Pollo Funghi Chicken & Mushroom'],
            ['id' => 169, 'category_id' => 45, 'item_name' => 'Pollo Special 11" Deep Pan', 'price' => 9.49, 'description' => 'Pollo Special Chicken Mushrooms, Pepper Garlic Butter & Fresh Tomatoes'],
            ['id' => 170, 'category_id' => 45, 'item_name' => 'Pollo Special 11" Thin', 'price' => 8.49, 'description' => 'Pollo Special Chicken Mushrooms, Peppers, Garlic Butter & Fresh Tomatoes'],
            ['id' => 171, 'category_id' => 45, 'item_name' => 'Pollo Special Family Size 16"', 'price' => 16.98, 'description' => 'Pollo Special Chicken Mushrooms, Peppers, Garlic Butter & Fresh Tomatoes'],
            ['id' => 172, 'category_id' => 45, 'item_name' => 'Prosciutto 11" Deep Pan', 'price' => 8.99, 'description' => 'Prosciutto Ham'],
            ['id' => 173, 'category_id' => 45, 'item_name' => 'Prosciutto 11" Thin', 'price' => 7.99, 'description' => 'Prosciutto Ham'],
            ['id' => 174, 'category_id' => 45, 'item_name' => 'Prosciutto Family Size 16"', 'price' => 15.98, 'description' => 'Prosciutto Ham'],
            ['id' => 175, 'category_id' => 45, 'item_name' => 'Prosciutto Funghi 11" Deep Pan', 'price' => 9.49, 'description' => 'Prosciutto Funghi Ham, Mushrooms'],
            ['id' => 176, 'category_id' => 45, 'item_name' => 'Prosciutto Funghi 11" Thin', 'price' => 8.49, 'description' => 'Prosciutto Funghi Ham, Mushrooms'],
            ['id' => 177, 'category_id' => 45, 'item_name' => 'Prosciutto Funghi Family Size 16"', 'price' => 16.98, 'description' => 'Prosciutto Funghi Ham, Mushrooms'],
            ['id' => 178, 'category_id' => 45, 'item_name' => 'Quatro Formaggi 11" Deep Pan', 'price' => 8.89, 'description' => 'Combination of four different Cheeses Quatro Formaggi'],
            ['id' => 179, 'category_id' => 45, 'item_name' => 'Quatro Formaggi 11" Thin', 'price' => 7.89, 'description' => 'Combination of four different Cheeses Quatro Formaggi'],
            ['id' => 180, 'category_id' => 45, 'item_name' => 'Quatro Formaggi Family Size 16"', 'price' => 15.98, 'description' => 'Combination of four different Cheeses Quatro Formaggi'],
            ['id' => 181, 'category_id' => 45, 'item_name' => 'Rostica 11" Deep Pan', 'price' => 9.99, 'description' => 'Rostica Ham, Pepperoni, Onions, Green Peppers, Cheddar Cheese'],
            ['id' => 182, 'category_id' => 45, 'item_name' => 'Rostica 11" Thin', 'price' => 8.99, 'description' => 'Rostica Ham, Pepperoni, Onions, Green Peppers, Cheddar Cheese'],
            ['id' => 183, 'category_id' => 45, 'item_name' => 'Rostica Family Size 16"', 'price' => 17.98, 'description' => 'Rostica Ham, Pepperoni, Onions, Green Peppers, Cheddar Cheese'],
            ['id' => 184, 'category_id' => 45, 'item_name' => 'Salami 11" Deep Pan', 'price' => 8.99, 'description' => 'Salami Salami Sausage'],
            ['id' => 185, 'category_id' => 45, 'item_name' => 'Salami 11" Thin', 'price' => 7.99, 'description' => 'Salami Salami Sausage'],
            ['id' => 186, 'category_id' => 45, 'item_name' => 'Salami Family Size 16"', 'price' => 15.98, 'description' => 'Salami Salami Sausage'],
            ['id' => 187, 'category_id' => 45, 'item_name' => 'Sanvito Pizza 11" Deep Pan', 'price' => 9.49, 'description' => 'Sanvito Pizza Ham & Chicken'],
            ['id' => 188, 'category_id' => 45, 'item_name' => 'Sanvito Pizza 11" Thin', 'price' => 8.49, 'description' => 'Sanvito Pizza Ham & Chicken'],
            ['id' => 189, 'category_id' => 45, 'item_name' => 'Sanvito Pizza Family Size 16"', 'price' => 16.98, 'description' => 'Sanvito Pizza Ham & Chicken'],
            ['id' => 190, 'category_id' => 45, 'item_name' => 'Sea Food 11" Deep Pan', 'price' => 12.99, 'description' => 'Sea Food Tuna, Mussels, Cockles, Prawns & Calamari, & Garlic Butter'],
            ['id' => 191, 'category_id' => 45, 'item_name' => 'Sea Food 11" Thin', 'price' => 11.99, 'description' => 'Sea Food Tuna, Mussels, Cockles, Prawns & Calamari, Anchovies & Garlic Butter'],
            ['id' => 192, 'category_id' => 45, 'item_name' => 'Sea Food Family Size 16"', 'price' => 23.98, 'description' => 'Sea Food Tuna, Mussels, Cockles, Prawns & Calamari, & Garlic Butter'],
            ['id' => 193, 'category_id' => 45, 'item_name' => 'Spicy BBQ Chicken 11" Deep Pan', 'price' => 9.49, 'description' => 'Spicy BBQ Chicken Spicy Chicken, BBQ Sauce, Mixed Peppers'],
            ['id' => 194, 'category_id' => 45, 'item_name' => 'Spicy BBQ Chicken 11" Thin', 'price' => 8.49, 'description' => 'Spicy BBQ Chicken Spicy Chicken, BBQ Sauce, Mixed Peppers'],
            ['id' => 195, 'category_id' => 45, 'item_name' => 'Spicy BBQ Chicken Family Size 16"', 'price' => 16.98, 'description' => 'Spicy BBQ Chicken Spicy Chicken, BBQ Sauce, Mixed Peppers'],
            ['id' => 196, 'category_id' => 45, 'item_name' => 'Spicy Beef 11" Deep Pan', 'price' => 8.99, 'description' => 'Spicy Beef, Onions'],
            ['id' => 197, 'category_id' => 45, 'item_name' => 'Spicy Beef 11" Thin', 'price' => 7.99, 'description' => 'Spicy Beef, Onions'],
            ['id' => 198, 'category_id' => 45, 'item_name' => 'Spicy Beef Family Size 16"', 'price' => 15.98, 'description' => 'Spicy Beef, Onions'],
            ['id' => 199, 'category_id' => 45, 'item_name' => 'Taste Of Italy 11" Deep Pan', 'price' => 9.99, 'description' => 'Pepperoni, Salami, Chicken, Green Peppers'],
            ['id' => 208, 'category_id' => 45, 'item_name' => 'Tuna 11" Deep Pan', 'price' => 10.99, 'description' => 'Tuna, Onions, Sweetcorn'],
            ['id' => 209, 'category_id' => 45, 'item_name' => 'Tuna 11" Thin', 'price' => 9.99, 'description' => 'Tuna, Onions, Sweetcorn'],
            ['id' => 210, 'category_id' => 45, 'item_name' => 'Tuna Family Size 16"', 'price' => 19.98, 'description' => 'Tuna, Onions, Sweetcorn'],
            ['id' => 211, 'category_id' => 45, 'item_name' => 'Vegetarian Combination 11" Deep Pan', 'price' => 8.89, 'description' => 'Five Vegetable toppings of your choice Vegetarian Combination'],
            ['id' => 212, 'category_id' => 45, 'item_name' => 'Vegetarian Combination 11" Thin', 'price' => 7.89, 'description' => 'Five Vegetable toppings of your choice Vegetarian Combination'],
            ['id' => 213, 'category_id' => 45, 'item_name' => 'Vegetarian Combination Family Size 16"', 'price' => 15.78, 'description' => 'Five Vegetable toppings of your choice Vegetarian Combination'],
            ['id' => 214, 'category_id' => 89, 'item_name' => 'CHICKEN TIKKA DONNER AND PEPPERONI 11" Deep Pan', 'price' => 9.99, 'description' => null],
            ['id' => 215, 'category_id' => 89, 'item_name' => 'CHICKEN TIKKA DONNER AND PEPPERONI 11" Thin', 'price' => 9.49, 'description' => null],
            ['id' => 216, 'category_id' => 89, 'item_name' => 'HOT LOVER 11" Deep Pan', 'price' => 9.49, 'description' => 'Pepperoni, Spicy Beef, Onions, Green Peppers, Cheddar Cheese & Jalapenos'],
            ['id' => 217, 'category_id' => 89, 'item_name' => 'HOT LOVER 11" Thin', 'price' => 8.99, 'description' => 'Pepperoni, Spicy Beef, Onions, Green Peppers, Cheddar Cheese & Jalapenos'],
            ['id' => 218, 'category_id' => 89, 'item_name' => 'MEAT FEAST 11" Deep Pan', 'price' => 9.99, 'description' => 'Ham, Salami, Garlic Sausage, Pepperoni, Spicy Beef'],
            ['id' => 219, 'category_id' => 89, 'item_name' => 'MEAT FEAST 11" Thin', 'price' => 9.49, 'description' => 'Ham, Salami, Garlic Sausage, Pepperoni, Spicy Beef'],
            ['id' => 220, 'category_id' => 89, 'item_name' => 'PENTATHLON 11" Deep Pan', 'price' => 9.99, 'description' => 'Mushrooms, Ham, Chicken, Pepperoni'],
            ['id' => 221, 'category_id' => 89, 'item_name' => 'PENTATHLON 11" Thin', 'price' => 9.49, 'description' => 'Mushrooms, Ham, Chicken, Pepperoni'],
            ['id' => 222, 'category_id' => 89, 'item_name' => 'PROSCIUTTO FUNGHI 11" Deep Pan', 'price' => 9.49, 'description' => 'Ham, Mushrooms'],
            ['id' => 223, 'category_id' => 89, 'item_name' => 'PROSCIUTTO FUNGHI 11" Deep Pan', 'price' => 9.49, 'description' => 'Ham, Mushrooms'],
            ['id' => 224, 'category_id' => 89, 'item_name' => 'PROSCIUTTO FUNGHI 11" Thin', 'price' => 8.99, 'description' => 'Ham, Mushrooms'],
            ['id' => 225, 'category_id' => 89, 'item_name' => 'ROSTICA 11" Deep Pan', 'price' => 9.99, 'description' => 'Ham, Pepperoni, Onions, Green Peppers Cheddar Cheese'],
            ['id' => 226, 'category_id' => 89, 'item_name' => 'ROSTICA 11" Thin', 'price' => 9.49, 'description' => 'Ham, Pepperoni, Onions, Green Peppers Cheddar Cheese'],
            ['id' => 227, 'category_id' => 89, 'item_name' => 'SANVITO PIZZA 11" Deep Pan', 'price' => 9.49, 'description' => 'Ham & Chicken'],
            ['id' => 228, 'category_id' => 89, 'item_name' => 'SANVITO PIZZA 11" Thin', 'price' => 8.99, 'description' => 'Ham & Chicken'],
            ['id' => 229, 'category_id' => 89, 'item_name' => 'TOSCANA 11" Deep Pan', 'price' => 9.49, 'description' => 'Ham, Mushrooms, Onions, Pepperoni'],
            ['id' => 230, 'category_id' => 89, 'item_name' => 'TOSCANA 11" Thin', 'price' => 8.99, 'description' => 'Ham, Mushrooms, Onions, Pepperoni'],
            ['id' => 231, 'category_id' => 89, 'item_name' => 'TROPICANA 11" Deep Pan', 'price' => 9.49, 'description' => 'Ham, Pineapple'],
            ['id' => 232, 'category_id' => 89, 'item_name' => 'TROPICANA 11" Thin', 'price' => 8.99, 'description' => 'Ham, Pineapple'],
            ['id' => 233, 'category_id' => 46, 'item_name' => 'Calzone (Folded Pizza)', 'price' => 8.59, 'description' => 'Ham, Mushrooms, Pepperoni, Salami & Garlic Sausage'],
            ['id' => 234, 'category_id' => 46, 'item_name' => 'Calzone Kebab (Folded Pizza)', 'price' => 8.29, 'description' => 'Doner Meat & Choice of Sauce (Chilli or Garlic Mayo)'],
            ['id' => 235, 'category_id' => 46, 'item_name' => 'Calzone Kiev (Folded Pizza)', 'price' => 8.59, 'description' => 'Mushrooms, Ham, Chicken, Garlic Butter & Cheddar Cheese'],
        ];

        foreach ($items as $item) {
            DB::table('menu_items')->insert([
                'id' => $item['id'],
                'category_id' => $item['category_id'],
                'item_name' => $item['item_name'],
                'price' => $item['price'],
                'description' => $item['description']
            ]);
        }
    }
} 